#!/bin/bash

HOST=localhost
#PORT=8080
PORT=$1

# n>20 for wilcoxon
RUNS=100

OUTPUT="tmp.${HOST}__$PORT.$RANDOM"
set -e

echo -n "Measuring..."

# throwaway, get into steady state
./httpttfb $HOST $PORT $RUNS 1>/dev/null
echo -n "(dry run) " 
# proper measurement runs
for i in 1 2 3 4 5; do
    ./httpttfb $HOST $PORT $RUNS >> $OUTPUT.$i
    echo -n "$i "
    sleep 2
done

echo "done"
./postprocess.py $OUTPUT
