#!/bin/bash

HOST=localhost
#PORT=8080
PORT=$1

# n>20 for wilcoxon
RUNS=100

OUTPUT="tmp.${HOST}__$PORT.$RANDOM"
set -e

# throwaway, get into steady state
./httpttfb $HOST $PORT $RUNS 1>/dev/null

# proper measurement runs
./httpttfb $HOST $PORT $RUNS >> $OUTPUT.1
sleep 2
./httpttfb $HOST $PORT $RUNS >> $OUTPUT.2
sleep 2
./httpttfb $HOST $PORT $RUNS >> $OUTPUT.3
sleep 2
./httpttfb $HOST $PORT $RUNS >> $OUTPUT.4
sleep 2
./httpttfb $HOST $PORT $RUNS >> $OUTPUT.5

./postprocess.py $OUTPUT
